import type { TaskListItem, TaskSource } from "@/components/tasks/task-types";
import { mapApiTaskToListItem, type ApiTaskListItem } from "@/lib/tasks/map-api-task";

export const taskSources: TaskSource[] = ["github", "asana", "internal"];

export const sourceLabels: Record<TaskSource, string> = {
  github: "GitHub",
  asana: "Asana",
  internal: "Internal",
};

const rawMockTasks: ApiTaskListItem[] = [
  {
    id: "github-1",
    source: "github",
    team: "Backend Team",
    title: "API rate limiting",
    tool: "Python",
    status: "backlog",
    priority: "high",
    blocked: false,
    dueDate: "2026-06-11",
    progress: 80,
    timeLeft: "1 Week Left",
    doneCount: 12,
    blockedCount: 7,
    members: ["MG"],
  },
  {
    id: "github-2",
    source: "github",
    team: "Front End Team",
    title: "Dashboard layout",
    tool: "React",
    status: "backlog",
    priority: "medium",
    blocked: false,
    dueDate: "2026-06-18",
    progress: 70,
    timeLeft: "2 Weeks Left",
    doneCount: 8,
    blockedCount: 6,
    members: ["NH", "EM", "KB"],
  },
  {
    id: "github-3",
    source: "github",
    team: "Backend Team",
    title: "Auth middleware",
    tool: "Node",
    status: "doing",
    priority: "high",
    blocked: false,
    dueDate: "2026-06-10",
    progress: 55,
    timeLeft: "4 Days Left",
    doneCount: 6,
    blockedCount: 2,
    members: ["SC"],
  },
  {
    id: "github-4",
    source: "github",
    team: "Front End Team",
    title: "Task board UI",
    tool: "React",
    status: "review",
    priority: "medium",
    blocked: false,
    dueDate: "2026-06-09",
    progress: 90,
    timeLeft: "3 Days Left",
    doneCount: 10,
    blockedCount: 1,
    members: ["IP"],
  },
  {
    id: "github-5",
    source: "github",
    team: "Backend Team",
    title: "Deploy pipeline",
    tool: "GitHub Actions",
    status: "review",
    priority: "normal",
    blocked: false,
    dueDate: "2026-06-08",
    progress: 85,
    timeLeft: "2 Days Left",
    doneCount: 14,
    blockedCount: 0,
    members: ["LF"],
  },
  {
    id: "github-6",
    source: "github",
    team: "Front End Team",
    title: "Sidebar navigation",
    tool: "React",
    status: "done",
    priority: "low",
    blocked: false,
    dueDate: "2026-06-05",
    progress: 100,
    timeLeft: "Done",
    doneCount: 20,
    blockedCount: 0,
    members: ["KB"],
  },
  {
    id: "github-7",
    source: "github",
    team: "Backend Team",
    title: "Database migrations",
    tool: "SQL",
    status: "done",
    priority: "medium",
    blocked: false,
    dueDate: "2026-06-04",
    progress: 100,
    timeLeft: "Done",
    doneCount: 18,
    blockedCount: 0,
    members: ["MG", "SC"],
  },
  {
    id: "github-8",
    source: "github",
    team: "Product Ops",
    title: "Release notes",
    tool: "Markdown",
    status: "done",
    priority: "normal",
    blocked: false,
    dueDate: "2026-06-03",
    progress: 100,
    timeLeft: "Done",
    doneCount: 5,
    blockedCount: 0,
    members: [],
  },
  {
    id: "asana-1",
    source: "asana",
    team: "UX UI Team",
    title: "Wireframe review",
    tool: "Figma",
    status: "backlog",
    priority: "normal",
    blocked: false,
    dueDate: "2026-06-09",
    progress: 30,
    timeLeft: "5 Days Left",
    doneCount: 4,
    blockedCount: 1,
    members: ["RS"],
  },
  {
    id: "asana-2",
    source: "asana",
    team: "Marketing Team",
    title: "Landing page copy",
    tool: "Notion",
    status: "doing",
    priority: "low",
    blocked: false,
    dueDate: "2026-06-13",
    progress: 40,
    timeLeft: "1 Week Left",
    doneCount: 9,
    blockedCount: 2,
    members: ["UF", "TR"],
  },
  {
    id: "asana-3",
    source: "asana",
    team: "UX UI Team",
    title: "Design system tokens",
    tool: "Figma",
    status: "review",
    priority: "high",
    blocked: false,
    dueDate: "2026-06-07",
    progress: 75,
    timeLeft: "3 Days Left",
    doneCount: 11,
    blockedCount: 0,
    members: ["MI", "JP"],
  },
  {
    id: "asana-4",
    source: "asana",
    team: "Marketing Team",
    title: "Social campaign",
    tool: "Notion",
    status: "done",
    priority: "medium",
    blocked: false,
    dueDate: "2026-06-02",
    progress: 100,
    timeLeft: "Done",
    doneCount: 15,
    blockedCount: 0,
    members: ["TR"],
  },
  {
    id: "internal-1",
    source: "internal",
    team: "Product Ops",
    title: "Sprint planning",
    tool: "Internal",
    status: "backlog",
    priority: "urgent",
    blocked: true,
    dueDate: "2026-06-07",
    progress: 10,
    timeLeft: "3 Days Left",
    doneCount: 1,
    blockedCount: 3,
    members: ["BA"],
  },
  {
    id: "internal-2",
    source: "internal",
    team: "QA Release",
    title: "Regression checklist",
    tool: "Checklist",
    status: "doing",
    priority: "high",
    blocked: false,
    dueDate: "2026-06-15",
    progress: 65,
    timeLeft: "10 Days Left",
    doneCount: 11,
    blockedCount: 3,
    members: ["QA", "ER"],
  },
  {
    id: "internal-3",
    source: "internal",
    team: "Product Ops",
    title: "Stakeholder update",
    tool: "Slides",
    status: "done",
    priority: "normal",
    blocked: false,
    dueDate: "2026-06-01",
    progress: 100,
    timeLeft: "Done",
    doneCount: 7,
    blockedCount: 0,
    members: ["OD", "TU"],
  },
];

export const mockTasks: TaskListItem[] = rawMockTasks.map(mapApiTaskToListItem);
