import type { TaskListItem, TaskSource } from "@/components/tasks/task-row";

export const taskSources: TaskSource[] = ["github", "asana", "internal"];

export const sourceLabels: Record<TaskSource, string> = {
  github: "GitHub",
  asana: "Asana",
  internal: "Internal",
};

export const mockTasks: TaskListItem[] = [
  {
    id: "github-1",
    source: "github",
    title: "Backend Team",
    tool: "Python",
    status: "in progress",
    priority: "high",
    blocked: false,
    dueDate: "2026-06-11",
    progress: 80,
    timeLeft: "1 Week Left",
    doneCount: 12,
    blockedCount: 7,
    members: ["MG", "SC", "IP", "LF"],
  },
  {
    id: "github-2",
    source: "github",
    title: "Front End Team",
    tool: "React",
    status: "doing",
    priority: "medium",
    blocked: true,
    dueDate: "2026-06-18",
    progress: 70,
    timeLeft: "2 Weeks Left",
    doneCount: 8,
    blockedCount: 6,
    members: ["NH", "EM", "KB"],
  },
  {
    id: "asana-1",
    source: "asana",
    title: "UX UI Team",
    tool: "Figma",
    status: "completed",
    priority: "normal",
    blocked: false,
    dueDate: "2026-06-09",
    progress: 90,
    timeLeft: "5 Days Left",
    doneCount: 14,
    blockedCount: 4,
    members: ["RS", "MI", "JP"],
  },
  {
    id: "asana-2",
    source: "asana",
    title: "Marketing Team",
    tool: "Notion",
    status: "in progress",
    priority: "low",
    blocked: false,
    dueDate: "2026-06-13",
    progress: 40,
    timeLeft: "1 Week Left",
    doneCount: 19,
    blockedCount: 10,
    members: ["UF", "TR"],
  },
  {
    id: "internal-1",
    source: "internal",
    title: "Product Ops",
    tool: "Internal",
    status: "todo",
    priority: "urgent",
    blocked: true,
    dueDate: "2026-06-07",
    progress: 35,
    timeLeft: "3 Days Left",
    doneCount: 5,
    blockedCount: 9,
    members: ["BA", "OD", "TU"],
  },
  {
    id: "internal-2",
    source: "internal",
    title: "QA Release",
    tool: "Checklist",
    status: "doing",
    priority: "high",
    blocked: false,
    dueDate: "2026-06-15",
    progress: 65,
    timeLeft: "10 Days Left",
    doneCount: 11,
    blockedCount: 3,
    members: ["QA", "ER", "PM"],
  },
];
